# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LottoUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtGui import QPixmap
from typing import MappingView
from PyQt5 import QtCore, QtGui, QtWidgets
import time
import playsound
import DrawLots
import sys
from PyQt5.QtCore import *


class Ui_Lotto(object):
    def setupUi(self, Lotto):
        Lotto.setObjectName("Lotto")
        Lotto.resize(1280, 800)
        self.centralwidget = QtWidgets.QWidget(Lotto)
        self.centralwidget.setObjectName("centralwidget")
        self.Main_Photo = QtWidgets.QLabel(self.centralwidget)
        self.Main_Photo.setGeometry(QtCore.QRect(10, 0, 1280, 800))
        self.Main_Photo.setText("")
        self.Main_Photo.setObjectName("Main_Photo")
        pixmap = QPixmap('Things/Main_Image.png')
        self.Main_Photo.setPixmap(pixmap)
        self.DrawLotsButton = QtWidgets.QPushButton(self.centralwidget)
        self.DrawLotsButton.setGeometry(QtCore.QRect(450, 590, 361, 131))
        self.DrawLotsButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.DrawLotsButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            "Things/3CAADF3C-D4C0-4051-B441-D777CAA9042E.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DrawLotsButton.setIcon(icon)
        self.DrawLotsButton.setIconSize(QtCore.QSize(391, 131))
        self.DrawLotsButton.setAutoRepeatDelay(300)
        self.DrawLotsButton.setObjectName("DrawLotsButton")
        self.percentage = QtWidgets.QTextEdit(self.centralwidget)
        self.percentage.setGeometry(QtCore.QRect(40, 30, 211, 141))
        font = QtGui.QFont()
        font.setFamily("D2Coding")
        font.setBold(True)
        font.setWeight(75)
        self.percentage.setFont(font)
        self.percentage.setAutoFillBackground(False)
        self.percentage.setObjectName("percentage")
        self.A_Label = QtWidgets.QLabel(self.centralwidget)
        self.A_Label.setGeometry(QtCore.QRect(440, 30, 418, 475))
        self.A_Label.setText("")
        self.A_Label.setObjectName("A_Label")
        self.B_Label = QtWidgets.QLabel(self.centralwidget)
        self.B_Label.setGeometry(QtCore.QRect(440, 30, 418, 475))
        self.B_Label.setText("")
        self.B_Label.setObjectName("B_Label")

        Lotto.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Lotto)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 24))
        self.menubar.setObjectName("menubar")
        Lotto.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Lotto)
        self.statusbar.setObjectName("statusbar")
        Lotto.setStatusBar(self.statusbar)

        self.retranslateUi(Lotto)
        QtCore.QMetaObject.connectSlotsByName(Lotto)
        self.DrawLotsButton.clicked.connect(self.BBobggi)

    def PlayDDuhuk(self):
        playsound.playsound("Sound\DDuhukSound.mp3", False)

    def PlayRubuduk(self):
        playsound.playsound("Sound\Rubuduk.mp3", False)

    def PlayWow1(self):
        playsound.playsound("Sound\Wow1.wav", False)

    def PlayYeah(self):
        playsound.playsound("Sound\YEAH!.mp3", False)

    def PlayBBabam(self):
        playsound.playsound("Sound\BBabam.wav", False)

    def PlayWow2(self):
        playsound.playsound("Sound\Wow 2.wav", False)

    def BBobggi(self):
        self.A_Label.setPixmap(QPixmap())
        BPixmap = QPixmap("Things/Dugudugu.jpeg")
        BPixmap.scaledToWidth(418)
        BPixmap.scaledToHeight(475)
        self.B_Label.setPixmap(BPixmap)
        awnser = DrawLots.MainLot()
        self.qPixmapFileVar = QPixmap()
        noPixmap = QPixmap()
        playsound.playsound("Sound\Dugudugu_sound.mp3", False)

        if awnser == "꽝":

            self.qPixmapFileVar.load("Things/GGwang.png")
            self.qPixmapFileVar.scaled(418, 475)
            QtCore.QTimer.singleShot(
                3800, lambda: self.A_Label.setPixmap(self.qPixmapFileVar))
            QtCore.QTimer.singleShot(
                3800, lambda: self.B_Label.setPixmap(noPixmap))
            QtCore.QTimer.singleShot(3900, lambda: self.PlayDDuhuk())
        elif awnser == "2000원":

            self.qPixmapFileVar.load("Things/2000.png")
            self.qPixmapFileVar.scaled(418, 475)
            QtCore.QTimer.singleShot(
                3800, lambda: self.A_Label.setPixmap(self.qPixmapFileVar))
            QtCore.QTimer.singleShot(
                3800, lambda: self.B_Label.setPixmap(noPixmap))
            QtCore.QTimer.singleShot(3700, lambda: self.PlayRubuduk())
        elif awnser == "3000원":

            self.qPixmapFileVar.load("Things/3000.png")
            self.qPixmapFileVar.scaled(418, 475)
            QtCore.QTimer.singleShot(
                3800, lambda: self.A_Label.setPixmap(self.qPixmapFileVar))
            QtCore.QTimer.singleShot(
                3800, lambda: self.B_Label.setPixmap(noPixmap))
            QtCore.QTimer.singleShot(3900, lambda: self.PlayWow1())
        elif awnser == "20000원":

            self.qPixmapFileVar.load("Things/20000.png")
            self.qPixmapFileVar.scaled(418, 475)
            QtCore.QTimer.singleShot(
                3800, lambda: self.A_Label.setPixmap(self.qPixmapFileVar))
            QtCore.QTimer.singleShot(
                3800, lambda: self.B_Label.setPixmap(noPixmap))
            QtCore.QTimer.singleShot(3900, lambda: self.PlayYeah())
        elif awnser == "200000원":

            self.qPixmapFileVar.load("Things/200000.png")
            self.qPixmapFileVar.scaled(418, 475)
            QtCore.QTimer.singleShot(
                3800, lambda: self.A_Label.setPixmap(self.qPixmapFileVar))
            QtCore.QTimer.singleShot(
                3800, lambda: self.B_Label.setPixmap(noPixmap))
            QtCore.QTimer.singleShot(3900, lambda: self.PlayBBabam()())
        elif awnser == "1000000원":

            self.qPixmapFileVar.load("Things/1000000.png")
            self.qPixmapFileVar.scaled(418, 475)
            QtCore.QTimer.singleShot(
                3800, lambda: self.A_Label.setPixmap(self.qPixmapFileVar))
            QtCore.QTimer.singleShot(
                3800, lambda: self.B_Label.setPixmap(noPixmap))
            QtCore.QTimer.singleShot(3900, lambda: self.PlayWow2())

    def retranslateUi(self, Lotto):
        _translate = QtCore.QCoreApplication.translate
        Lotto.setWindowTitle(_translate("Lotto", "MainWindow"))
        self.percentage.setHtml(_translate("Lotto", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                           "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                           "p, li { white-space: pre-wrap; }\n"
                                           "</style></head><body style=\" font-family:\'D2Coding\'; font-size:13pt; font-weight:600; font-style:normal;\">\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; color:#f90000;\">확률표</span></p>\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#f27a00;\">꽝 : 69.89%</span></p>\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#d1e800;\">2000원 : 20%</span></p>\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#00ef00;\">3000원 : 10%</span></p>\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#006700;\">20000원 : 1%</span></p>\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#00f2ff;\">200000원 : 0.1%</span></p>\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0000ff;\">1000000원 : 0.001%</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Lotto = QtWidgets.QMainWindow()
    ui = Ui_Lotto()
    ui.setupUi(Lotto)
    Lotto.show()
    sys.exit(app.exec_())
